"""v1_init

Revision ID: 2eef554a6b8e
Revises: 
Create Date: 2024-10-22 13:00:51.256386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2eef554a6b8e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('key_feature', sa.Text(), nullable=True),
    sa.Column('personality', sa.Text(), nullable=True),
    sa.Column('tools', sa.JSON(), nullable=True),
    sa.Column('profile_image', sa.String(length=255), nullable=True),
    sa.Column('video', sa.String(length=255), nullable=True),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('focus_group_survey', sa.JSON(), nullable=True),
    sa.Column('own_data', sa.JSON(), nullable=True),
    sa.Column('top_ideas', sa.JSON(), nullable=True),
    sa.Column('file_url', sa.String(length=255), nullable=True),
    sa.Column('api_data', sa.String(length=255), nullable=True),
    sa.Column('survey', sa.String(length=255), nullable=True),
    sa.Column('group_id', sa.Text(), nullable=True),
    sa.Column('vector_id', sa.String(length=36), nullable=True),
    sa.Column('is_chatbot', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_agents_id'), 'agents', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agents_id'), table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###
